title: senan kelly
description: irish software engineer
url: https://senan.xyz/
repo: https://github.com/sentriz/xyz/
timezone: Europe/Dublin
locale: en_IE
markdown: kramdown
highlighter: rouge
permalink: pretty
sass:
  style: compressed
  sass_dir: _sass
kramdown:
  input: GFM
  hard_wrap: false
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Senan Kelly
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - readme.md
  - vendor
plugins:
  - jekyll-feed
  - jekyll-sitemap
