#!/usr/bin/env fish

# npm install --save-dev prettier prettier-plugin-go-template prettier-plugin-tailwindcss
# prettier --write --parser go-template ./*.partial ./**/*.tmpl

readlink -f -- ./*.partial ./**.tmpl | entr -s '
export DATE=(date +%s);
tmplc base.partial ./*.tmpl;
tmplc base.partial post.partial ./20*/**/*.tmpl;
' &

yes | npx tailwindcss --input styles/style.css --output styles/build.css --watch &

serve :4000 &

trap 'kill (jobs -p) 2>/dev/null' SIGINT

wait
